name: easycrop_e1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase Packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.6

  # Package for date formatting
  intl: ^0.18.1

  # Other Packages
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  csv: ^6.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  http: ^1.2.1
  file_saver: ^0.2.12    # ðŸ‘ˆ à¹€à¸žà¸´à¹ˆà¸¡à¸šà¸£à¸£à¸—à¸±à¸”à¸™à¸µà¹‰
  permission_handler: ^11.3.1 # ðŸ‘ˆ à¹à¸¥à¸°à¸šà¸£à¸£à¸—à¸±à¸”à¸™à¸µà¹‰
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

# --- START: à¸ªà¹ˆà¸§à¸™à¸—à¸µà¹ˆà¹€à¸žà¸´à¹ˆà¸¡à¹€à¸‚à¹‰à¸²à¸¡à¸²à¸ªà¸³à¸«à¸£à¸±à¸šà¸à¸²à¸£à¸ªà¸£à¹‰à¸²à¸‡à¹„à¸­à¸„à¸­à¸™ ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  # --- à¹à¸à¹‰à¹„à¸‚à¸ªà¹ˆà¸§à¸™à¸™à¸µà¹‰ ---
  adaptive_icon_background: "#00FFFFFF" # <--- à¸ªà¸µà¹‚à¸›à¸£à¹ˆà¸‡à¹ƒà¸ª (Transparent)
  adaptive_icon_foreground: "assets/icon/icon.png"
# --- END: à¸ªà¹ˆà¸§à¸™à¸—à¸µà¹ˆà¹€à¸žà¸´à¹ˆà¸¡à¹€à¸‚à¹‰à¸²à¸¡à¸² ---